config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  get '/search', to: 'flats#search'

  resources :bookings

  resources :flats do
    resources :flat_pics
  end

  get 'welcome/index'

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: "my_registrations" }

  scope module: 'users' do
    resources :users
  end

  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [ :facebook ]

  has_many :flats
  has_many :bookings

  has_attached_file :avatar,
    styles: { big: "600x600#", medium: "300x300#", thumb: "100x100#" },
    :default_url => "default_user_picture.svg"

  validates_attachment_content_type :avatar,
    content_type: /\Aimage\/.*\z/

  def self.find_for_facebook_oauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.picture = auth.info.image
      user.token = auth.credentials.token
      user.token_expiry = Time.at(auth.credentials.expires_at)
    end
  end

  def image
    if avatar.file? || picture.nil?
      return avatar.url(:big)
    else
      return "#{picture}?type=large"
    end
  end

  def mini_pic
    if avatar.file? || picture.nil?
      return avatar.url(:thumb)
    else
      return "#{picture}?type=square"
    end
  end

  def name
    if first_name || last_name
      "#{first_name} #{last_name}"
    else
      email
    end
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
# app/controllers/users/omniauth_callbacks_controller.rb

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env["omniauth.auth"])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController
  before_action :set_user
  before_action :current_user?, only: [:edit, :update, :destroy]

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :avatar)
    end

    def current_user?
      if current_user != @user
        not_found
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :avatar)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= image_tag @user.image, size: "225x225", alt: @user.name %>
    <%= f.input :avatar, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, {class: "btn btn-primary"} %>
  </div>
<% end %>

app/views/users/users/edit.html.erb
<div class="container padded">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
      <h1>Edit my profile</h1>

      <%= render 'form' %>
      <br>

      <%= link_to 'Show', @user %> |
      <%= link_to 'Back', root_path %>
    </div>
  </div>
</div>

app/views/users/users/show.html.erb
<div class="container padded">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">

      <h1><%= @user.first_name %> <%= @user.last_name %></h1>

      <%= image_tag @user.image, size: "225x225", alt: @user.name %>

      <h2>My flats</h2>
      <table class="table">
        <tr>
        <th>Flat</th>
        <th>Address</th>
        <% if @user == current_user %>
          <th class="text-center">Edit</th>
          <th class="text-center">Destroy</th>
          <th class="text-center">Edit Pics</th>
        <% end %>
          </tr>
        <% @user.flats.each do |flat| %>
          <tr>
            <td><%= link_to flat_path(flat) do %>
              <%= flat.name %>
            <% end %></td>
            <td>
              <%= link_to flat_path(flat) do %>
                <%= flat.address %>
              <% end %>
            </td>
            <% if @user == current_user %>
              <td class="text-center"><%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_flat_path(flat) %></td>
              <td class="text-center"><%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, flat_path(flat), method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <td class="text-center"><%= link_to '<i class="fa fa-camera"></i>'.html_safe, flat_flat_pics_path(flat) %></td>
            <% end %>
          </tr>
        <% end %>
      </table>

      <% if @user == current_user %>

        <%= link_to "Add a flat", new_flat_path, {class: "btn btn-primary"} %>
        <br>
        <br>

        <h2>My Trips</h2>

        <table class="table">
          <tr>
            <th>Flat</th>
            <th>Owner</th>
            <th>Start date</th>
            <th>End date</th>
            <th>Show</th>
            </tr>
            <% @user.bookings.each do |booking| %>
            <tr>
              <td>
                <%= link_to flat_path(booking.flat) do%>
                  <%= booking.flat.name %>
                <% end %>
              </td>
              <td>
                <%= link_to user_path(booking.flat.user) do%>
                  <%= booking.flat.user.name %>
                <% end %>
              </td>
              <td><%= booking.start_date %></td>
              <td><%= booking.end_date %></td>
              <td><%= link_to '<i class="fa fa-eye"></i>'.html_safe, booking %></td>
            </tr>
          <% end %>
        </table>

        <div class="btn-group" role="group">
          <%= link_to "Edit profile", edit_user_path, {class: "btn btn-primary"} %>
          <%= link_to "Edit my account settings", edit_user_registration_path(@user), {class: "btn btn-primary"} %>
        </div>
      <% end %>
    </div>
  </div>
</div>