config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  get '/search', to: 'flats#search'

  resources :bookings

  resources :flats do
    resources :flat_pics
  end

  get 'welcome/index'

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: "my_registrations" }

  scope module: 'users' do
    resources :users
  end

  root 'welcome#index'

end

app/models/flat_pic.rb
class FlatPic < ActiveRecord::Base
    has_attached_file :picture,
    styles: { medium: "300x200#", thumb: "100x100#", large: "1920x1280>" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/

  belongs_to :flat
  #validates :picture, presence: true

end

app/controllers/flat_pics_controller.rb
class FlatPicsController < ApplicationController
  before_action :find_flat
  before_action :set_flat_pic, only: [:show, :edit, :update, :destroy]
  before_action :current_user?

  # GET /flat_pics
  def index
    @flat_pics = @flat.flat_pics
    @flat_pic = FlatPic.new
  end

  # GET /flat_pics/1
  def show
    @flat.flat_pics(@flat_pic)
  end

  # GET /flat_pics/new
  def new
    @flat_pic = FlatPic.new
  end

  # GET /flat_pics/1/edit
  def edit
  end

  # POST /flat_pics
  def create
    @flat_pic = @flat.flat_pics.build(flat_pic_params)

    if @flat_pic.save
      redirect_to flat_flat_pics_path(@flat), notice: 'Your image was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /flat_pics/1
  def update
    if @flat_pic.update(flat_pic_params)
      redirect_to flat_flat_pics_path(@flat), notice: 'Your image was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /flat_pics/1
  def destroy
    @flat_pic.destroy
    redirect_to flat_flat_pics_path(@flat), notice: 'Your image was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flat_pic
      @flat_pic = @flat.flat_pics.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def flat_pic_params
      params.require(:flat_pic).permit(:description, :flat_id, :picture)
    end

    def find_flat
      @flat = Flat.find(params[:flat_id])
    end

    def current_user?
      if current_user != @flat.user
        not_found
      end
    end
end

app/helpers/flat_pics_helper.rb
module FlatPicsHelper
end

app/views/flat_pics/_form.html.erb
<%= semantic_form_for [@flat, @flat_pic] do |f| %>
<div class="form-inputs">
  <%= f.input :picture, as: :file%>
</div>

  <%= f.action :submit, as: :button, label: 'Upload Pic', :class => "btn btn-primary" %>
  <br>
  <br>
<div class="form-actions btn-group">


  <%= link_to 'My Listings', user_path(current_user), {class: "btn btn-primary"}  %>
  <%= link_to 'This Venue', flat_path(@flat), {class: "btn btn-primary"}  %>
</div>
<% end %>

app/views/flat_pics/edit.html.erb
<div class = "container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1"><h1>Editing Flat Pic</h1>

        <%= render 'form' %>

        <div class="btn-group" role="group">
        <%= link_to 'Show', flat_flat_pic_path(@flat, @flat_pic) %>
        <%= link_to 'Back', flat_flat_pics_path(@flat) %>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/flat_pics/index.html.erb
<div class = "container padded">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3">

      <% if notice %>
        <p id="notice" class="alert alert-success alert-dismissible">
          <%= notice %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </p>
      <% end %>

      <h1><%= @flat.city %></h1>
      <table class = "table">
        <thead>
          <tr>
            <th>Flat</th>
            <th>Destroy</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @flat_pics.each do |flat_pic| %>
          <tr>
            <td><%= image_tag flat_pic.picture.url(:thumb) %></td>
            <td><%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, flat_flat_pic_path(@flat, flat_pic), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <br>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/flat_pics/new.html.erb
<div class = "container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3">
      <h1>New Flat Pic</h1>

      <%= render 'form' %>

      <%= link_to 'Back', flat_flat_pics_path(@flat) %>

    </div>
  </div>
</div>

app/views/flat_pics/show.html.erb
<div class = "container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
      <% if notice %>
        <p id="notice" class="alert alert-success alert-dismissible">
          <%= notice %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </p>
      <% end %>

      <p>
        <strong>Description:</strong>
        <%= @flat_pic.description %>
      </p>

      <p>
        <%= image_tag @flat_pic.picture.url(:medium) %>
      </p>

      <%#= link_to 'Edit', edit_flat_flat_pic_path(@flat) %>
      <%#= link_to 'Back', flat_flat_pics_path(@flat) %>
    </div>
  </div>
</div>