config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  get '/search', to: 'flats#search'

  resources :bookings

  resources :flats do
    resources :flat_pics
  end

  get 'welcome/index'

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: "my_registrations" }

  scope module: 'users' do
    resources :users
  end

  root 'welcome#index'

end

app/models/flat.rb
class Flat < ActiveRecord::Base
  has_many :bookings
  belongs_to :user
  has_many :flat_pics, dependent: :destroy

  validates :user, :name, :city, :price, :flat_pics, :address, presence: true

  #addes to allow to integrate flat_pic form in flat form
  accepts_nested_attributes_for :flat_pics

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def user_bg
    "background-image: url(#{flat_pics.first.picture.url(:large)});"
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:show, :index, :search]
  before_action :current_user?, only: [:edit, :update, :destroy]

  # GET /flats
  def index
    @flats = Flat.all

    # Let's DYNAMICALLY build the markers for the view.
    @markers = Gmaps4rails.build_markers(@flats) do |flat, marker|
      marker.lat flat.latitude
      marker.lng flat.longitude
    end
  end

  def search
    # @flats = Flat.where(city: params[:city].capitalize)
    @flats = Flat.near(params[:address], 10) # to improve when geocoder works

    @markers = Gmaps4rails.build_markers(@flats) do |flat, marker|
      marker.lat flat.latitude
      marker.lng flat.longitude
    end
    render "index"
  end

  # GET /flats/1
  def show
        # Let's DYNAMICALLY build the markers for the view.
    @marker = Gmaps4rails.build_markers(@flat) do |flat, marker|
      marker.lat flat.latitude
      marker.lng flat.longitude
    end

  end

  # GET /flats/new
  def new
    @flat = Flat.new
    @flat.flat_pics.build
     #line added to integrate flat_pic form in flat form
  end

  # GET /flats/1/edit
  def edit
    #set the user as current user so that I can remove it from the form
    @flat.user = current_user
  end

  # POST /flats
  def create
    @flat = Flat.new(flat_params)
    #set the user as current user so that I can remove it from the form
    @flat.user = current_user
    if @flat.save
      redirect_to @flat, notice: 'Flat was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /flats/1
  def update
    if @flat.update(flat_params)
      redirect_to user_path(current_user), notice: 'Flat was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /flats/1
  def destroy
    @flat.destroy
    redirect_to flats_url, notice: 'Flat was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flat
      @flat = Flat.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def flat_params
      params.require(:flat).permit(:address, :name, :description, :user_id, :city, :accomodates, :price, :has_AC, :has_jacuzzi, flat_pics_attributes:[:description, :picture])
    end

    def current_user?
        if current_user != @flat.user
          not_found
      end
    end
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= semantic_form_for @flat do |f| %>
<%= f.inputs do %>
  <%#= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :address, id: "flat_address" %>
    <%= f.input :city %>
    <%= f.input :accomodates %>


    <%= f.input :price, prepend: '€', hint: "Example: 35" %>

<!-- This integrates the create flat_pic form into the flat create form -->
    <%= f.semantic_fields_for :flat_pics do |ff| %>
        <%= ff.input :picture, as: :file %>
    <% end %>
<!-- Also modified the flat model & controller new and params -->
  </div>

    <div class= "btn btn-primary">
    <%= f.button :submit, as: :button, class: "btn btn-primary" %>
    </div>
    <%= link_to 'Cancel', user_path(current_user), {class: "btn btn-primary"} %>
  <br>
  <% end %>
<% end %>

app/views/flats/_form_edit.html.erb
<%= simple_form_for(@flat) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :address, id: "flat_address" %>
    <%= f.input :city %>
    <%= f.input :accomodates %>

    <div class="form-inline">
      <div class="form-group">
        <label class="sr-only">Amount (in Euros)</label>
        <div class="input-group">
          <div class="input-group-addon">€</div>
        <div><%= f.input :price %></div>
        </div>
      </div>
    </div>

    <%= f.input :has_AC %>
    <%= f.input :has_jacuzzi %>

  </div>
  <div class="form-actions">
    <%= f.button :submit, {class: "btn btn-primary"} %>
    <%= link_to 'Delete Flat', flat_path(@flat), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
  </div>
  <br>
<% end %>

app/views/flats/edit.html.erb
<div class = "container padded">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3">
      <div class = "row">
        <h1>Editing Flat</h1>
        <%= render 'form_edit' %>
        <div class="btn-group">
          <%= link_to 'Show', @flat, {class: "btn btn-primary"} %>
          <%= link_to 'My Listings', user_path(current_user), {class: "btn btn-primary"} %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/flats/index.html.erb
<div class="map-wrapper">
  <div id="map_many" class="list-map"></div>
</div>

<div class="container">
  <div class = "row">
    <div class="col-sm-7">

      <% if notice %>
        <p id="notice" class="alert alert-success alert-dismissible">
          <%= notice %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </p>
      <% end %>

      <% @flats.each do |flat| %>
        <div class="col-xs-12 col-sm-6 text-center full-padded">
          <%= link_to (image_tag flat.flat_pics.first.picture.url(:medium), style: "max-width: 100%;"), flat  %>
          <p>
            <%= link_to flat.name, flat %>
            <br>
            <span class = "small text-muted"><%= flat.city %> · Beds : <%= flat.accomodates %> · <%= flat.price %> €/night</span>
          </p>
        </div>
      <% end %>
    </div>
  </div>
</div>

<br>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).on( 'ready', function() {
      handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map_many' } }, function(){
        markers = handler.addMarkers(<%= raw @markers.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
      });
    });
  <% end %>
<% end %>
<%#= link_to 'New Flat', new_flat_path %>

app/views/flats/new.html.erb
<div class = "container padded">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3">

        <h1>New Flat</h1>

        <%= render 'form' %>


    </div>
  </div>
</div>

app/views/flats/show.html.erb
<div class="show-image-container">
  <div class="show-cover-img" style="<%= @flat.user_bg %>"><%#= image_tag @flat.flat_pics.first.picture.url(:large) %></div>
</div>
<div class = "container padded">

  <% if notice %>
    <p id="notice" class="alert alert-success alert-dismissible">
      <%= notice %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </p>
  <% end %>

  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">

      <div class = "row">
        <div class = "col-md-3">
          <strong><%= @flat.name %></strong>
        </div>
      <div class = "col-md-9">
          <div class = row>
            <div class = "col-md-6">
              <div>
                <%= link_to 'Book Now', new_booking_path(user_id: @flat.user_id, flat_id: @flat.id), class: "btn btn-primary" %>
              </div>
            </div>
          </div>
        </div>
      </div>


      <hr>
      <div class = "row">
        <div class = "col-md-3">
          Space
        </div>
        <div class = "col-md-9">
          <div class = row>
            <div class = "col-md-6">
              <div>
                <small class = "text-muted">City:</small>
                <strong><%= @flat.city %></strong>
              </div>
              <div>
                <small class = "text-muted">Property Type:</small>
                <strong>Appartment</strong>
              </div>
              <div>
                <small class = "text-muted">Accomodates:</small>
                <strong><%= @flat.accomodates %>  </strong>
              </div>
              <div>
                <small class = "text-muted">Price:</small>
                <strong><%= @flat.price %> €</strong>
              </div>
            </div>
            <div class = "col-md-6">
              <div>
                <small class = "text-muted">Bathrooms:</small>
                <strong><%= 2 %></strong>
              </div>
              <div>
                <small class = "text-muted">Check In:</small>
                <strong><%= 11.00 %></strong>
              </div>
              <div>
                <small class = "text-muted">Check Out:</small>
                <strong><%= 13.00 %></strong>
              </div>
              <div>
                <small class = "text-muted">Host:</small>
                <strong>
                  <%= link_to user_path(@flat.user) do %>
                    <%= @flat.user.first_name %> <%= @flat.user.last_name %>
                  <% end %>
                </strong>
              </div>
              <div></div>
            </div>
          </div>
        </div>
      </div>
      <hr>
      <div class = "row">
        <div class = "col-md-3">
          Amenities
        </div>
        <div class = "col-md-9">
          <div class = row>
            <div class = "col-md-6">
              <div>
                <small class = "text-muted">Air-Conditing:</small>
                <strong><%= @flat.has_AC ? "Yes" : "No" %></strong>
              </div>
              <div>
                <small class = "text-muted">Jacuzzi:</small>
                <strong><%= @flat.has_jacuzzi ? "Yes" : "No" %></strong>
              </div>
              <div>
                <small class = "text-muted">Kitchen:</small>
                <strong>Yes</strong>
              </div>
              <div>
                <small class = "text-muted">Wifi:</small>
                <strong>Yes</strong>
              </div>
            </div>
            <div class = "col-md-6">
              <div>
                <small class = "text-muted">Heating:</small>
                <strong>Yes</strong>
              </div>
              <div>
                <small class = "text-muted">Breakfast:</small>
                <strong>No</strong>
              </div>
              <div>
                <small class = "text-muted">Free Parking</small>
                <strong>Yes</strong>
              </div>
              <div>
                <small class = "text-muted">Sheets:</small>
                <strong>Yes</strong>
              </div>
              <div></div>
            </div>
          </div>
        </div>
      </div>

      <hr>
      <div class = "row">
        <div class = "col-md-3">
          Description
        </div>
      <div class = "col-md-9">
          <div class = row>
            <div class = "col-md-6">
              <div>
                <small class = "text-muted"><%= @flat.description %></small>
              </div>
            </div>
          </div>
        </div>
      </div>

      <hr>
      <div class = "row">
        <div class = "col-md-3">
        </div>
      <div class = "col-md-9">
          <div class = row>
            <div class = "col-md-6">
              <div>
                <%= link_to 'Book Now', new_booking_path(user_id: @flat.user_id, flat_id: @flat.id), class: "btn btn-primary" %>
                <%= link_to 'More Flats', flats_path, {class: "btn btn-primary"} %>
              </div>
            </div>
          </div>
        </div>
      </div>


      <hr>

      <div class="row">
        <% @flat.flat_pics.each do |flat_pic| %>
          <div class="col-lg-4 col-md-6">
            <%= link_to flat_pic.picture.url(:large) do %>
              <%= image_tag flat_pic.picture.url(:medium)%>
            <% end %>
          </div>
        <%end%>
      </div>
    </div>
  </div>
</div>

<div id="map" class="flat-map"></div>


<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).on('ready', function() {
      handler = Gmaps.build('Google');
      handler.buildMap({ provider: { scrollwheel: false }, internal: { id: 'map' } }, function(){
        markers = handler.addMarkers(<%= raw @marker.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        handler.getMap().setZoom(16);
      });
    });
  <% end %>
<% end %>