config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  get '/search', to: 'flats#search'

  resources :bookings

  resources :flats do
    resources :flat_pics
  end

  get 'welcome/index'

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: "my_registrations" }

  scope module: 'users' do
    resources :users
  end

  root 'welcome#index'

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :flat
  belongs_to :user

  validates :user_id, :flat_id, :start_date, :end_date, presence: true
  validates :date_must_be_in_future, inclusion: { in: [true]}

   def date_must_be_in_future
    start_date > Date.today
   end

   def self.booked?(venue_id, check_in, check_out)
    @bookings = Booking.where(flat_id:venue_id)
    if @bookings.count == 0
      return false
    else
      @bookings.each do |booking|
        if booking.start_date.nil? || booking.start_date == 0
          return false
        elsif booking.start_date <= check_in && check_in <= booking.end_date
          return true
        elsif check_in <= booking.start_date && booking.start_date <= check_out
          return true
        else
          return false
        end
      end
     end
    end

    def self.start_date_after_end_date?(start_date, end_date)
    start_date > end_date
    end


end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]
  before_action :set_user_flat

  # GET /bookings
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  def create
    #Need to convert the two dates into Ruby dates
    start_date = DateTime.strptime(booking_params[:start_date], '%d/%m/%Y')
    end_date = DateTime.strptime(booking_params[:end_date], '%d/%m/%Y')
    @booking = Booking.new(start_date:start_date, end_date:end_date, user_id:current_user.id, flat_id:booking_params[:flat_id])
    @booking.user = current_user
    @booking.flat = Flat.find(booking_params[:flat_id])

    if Booking.booked?(booking_params[:flat_id], start_date, end_date)
      redirect_to new_booking_path(flat_id: booking_params[:flat_id]), notice: 'Sorry your venue is already booked at these dates'
    elsif Booking.start_date_after_end_date?(start_date, end_date)
      redirect_to new_booking_path(flat_id: booking_params[:flat_id]), notice: 'No time-machines, End date must be after Start date'
    elsif @booking.save
      redirect_to @booking, notice: 'Dear ' + @booking.user.name + ', your booking at ' + @booking.flat.name + ' was successfully created.'
      UserMailer.booking(@booking.user, @booking.flat, @booking.start_date, @booking.end_date).deliver
    else
      redirect_to new_booking_path(flat_id: booking_params[:flat_id]), notice: 'STOP living in the past, dates in the futur only please'
      #need to redirect (and not render) take the id of the flat)
    end
  end

  # PATCH/PUT /bookings/1
  def update
    if @booking.update(booking_params)
      redirect_to @booking, notice: 'Booking was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /bookings/1
  def destroy
    @booking.destroy
    redirect_to bookings_url, notice: 'Booking was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    def set_user_flat
      @user = current_user
      @flat = Flat.where(id: params[:flat_id]).first
    end

    # Only allow a trusted parameter "white list" through.
    def booking_params
      params.require(:booking).permit(:start_date, :end_date, :user_id, :flat_id)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= javascript_include_tag "bookings" %>
<%= simple_form_for(@booking, :html => {:class => 'form-vertical'}) do |f| %>

<%= f.error_notification %>
    <h1>Book this flat</h1>

    <% @bookings = Booking.where(flat_id: @flat.id) %>
    <% @bookings.each do |booking| %>
                  <p><%= booking.flat.name %> |
                 <%= booking.start_date %> |
                 <%= booking.end_date %></p>
              <% end %>
              <%= @flat.id %></p>

      <p>Name of venue : <%= @flat.name %></p>
      <p>Booking location : <%= @flat.city %></p>
  <br>

<div class="form-inputs">
<!-- took id name with inspect element and changed the js -->
  <%= f.input :start_date, as: :string %>
  <%= f.input :end_date, as: :string %>
<!-- end of js calendar -->


  <%= f.input :user_id, input_html: { value: @current_user }, as: :hidden %>
  <%= f.input :flat_id, input_html: { value: @flat.id }, as: :hidden %>
</div>
<br>

  <div class="form-actions btn-group">
    <%= f.button :submit, {class: "btn btn-success"} %>
    <%= link_to 'Other Flats', flats_path, {class: "btn btn-primary"} %>
  </div>
<% end %>
<br>

<div class = "padded"></div>

app/views/bookings/_form.html_backup.erb
<%= javascript_include_tag "bookings" %>
<%= simple_form_for( :booking, :html => {:class => 'form-vertical' }) do |f| %>

<%= f.error_notification %>
    <h1>Book this flat</h1>
      <p>Name of venue : <%=  %></p>
      <p>Booking location : <%=  %></p>
  <br>

  <div class="form-inputs">
  <!-- took id name with inspect element and changed the js -->
    <div id:"start_date" class="input-append date datepicker" data-date-format="dd-mm-yyyy"></div>
    <div id:"end_date" class="input-append date datepicker" data-date-format="dd-mm-yyyy"></div>

  <!-- end of js calendar -->
  </div>

<br>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>

<% end %>

<br>

<div class = "padded"></div>

<script type="text/javascript">
  $('.datepicker').datepicker();
</script>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form' %>

<%= link_to 'Show', @booking, {class: "btn btn-primary"} %>
<%= link_to 'Back', bookings_path, {class: "btn btn-primary"} %>

app/views/bookings/index.html.erb
<div class = "container">
  <div class="row padded">
    <div class="col-xs-10 col-xs-offset-1">

        <% if notice %>
          <p id="notice" class="alert alert-success alert-dismissible">
            <%= notice %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </p>
        <% end %>

        <div class = "row">

          <h1>Listing Bookings</h1>

          <table class = "table">
            <thead>
              <tr>
                <th>Flat</th>
                <th>Start date</th>
                <th>End date</th>
                <th>Show</th>
                <th>Edit</th>
                <th>Delete</th>
              </tr>
            </thead>

            <tbody>
              <% @bookings.each do |booking| %>
                <tr>
                  <td><%= booking.flat.name %></td>
                  <td><%= booking.start_date %></td>
                  <td><%= booking.end_date %></td>
                  <td><%= link_to '<i class="fa fa-eye"></i>'.html_safe, booking %></td>
                  <td><%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_booking_path(booking) %></td>
                  <td><%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
            </tbody>
          </table>

          <br>

          <%= link_to 'New Booking', flats_path, {class: "btn btn-primary"} %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<div class = "container">
  <div class="row padded">
    <div class="col-xs-10 col-xs-offset-1">

      <% if notice %>
        <p id="notice" class="alert alert-success alert-dismissible">
          <%= notice %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </p>
      <% end %>

      <div class = "row">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class = "container padded">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">

      <% if notice %>
        <p id="notice" class="alert alert-success alert-dismissible">
          <%= notice %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </p>
      <% end %>

      <p>
      <strong>Flat:</strong>
      <%= @booking.flat.name %>
      </p>
      <p>

      <strong>Booked by:</strong>
      <%= @booking.user.name %>

      </p>
      <p>
      <strong>Start date:</strong>
      <%= @booking.start_date %>
      </p>
      <p>
      <strong>End date:</strong>
      <%= @booking.end_date %>
      </p>
      <%#= link_to 'Edit', edit_booking_path(@booking), {class: "btn btn-primary"} %>
      <div class="btn-group" role="group">
        <%= link_to 'My Trips', user_path(current_user), {class: "btn btn-primary"} %>
        <%= link_to 'More Flats', flats_path, {class: "btn btn-primary"} %>
      </div>
    </div>
  </div>
</div>